# .github/workflows/ci.yml

# Nome do seu pipeline
name: Pipeline de Testes de QA

# "Triggers": Quando o pipeline deve rodar?
on:
  # Roda em todo 'push' para a branch 'main'
  push:
    branches: [ main ]
  # Roda em todo 'pull request' para a branch 'main'
  pull_request:
    branches: [ main ]

# "Jobs": O que fazer?
jobs:
  # Nome do job (pode ser qualquer nome)
  build-and-test:
    # "Runner": Em qual máquina virtual rodar?
    runs-on: ubuntu-latest # Vamos usar um Linux, é mais rápido

    steps:
    # Passo 1: Baixar o código do seu repositório
    - name: 1. Checkout do código
      uses: actions/checkout@v4

    # Passo 2: Configurar o Python
    - name: 2. Configurar Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # Passo 3: Instalar as dependências do requirements.txt
    - name: 3. Instalar dependências
      run: |
        pip install -r requirements.txt

    # Passo 4: Rodar os testes (o mesmo comando que você usou)
    - name: 4. Executar os testes (pytest)
      run: |
        pytest